### ISSUE TITLE
FSharp.Charting.Gtk cannot compile

### ISSUE THREAD

**Issue by mndrake** [fsharp/FSharp.Charting#67] opened 2015-01-29 20:36 UTC
#59 switched the version of ``OxyPlot.Core`` and ``OxyPlot.GtkSharp`` to 2014.1.546. This change created two compile errors due to breaking errors in the OxyPlot library. ``PlotControl`` and ``RefreshPlot`` in ``PlotModel`` are no longer available (and the master branch of ``FSharp.Charting.Gtk`` cannot be compiled).

**Comment by dsyme** [comment] 2015-01-30 23:38
Strange, it compiles on my machine using commit d6c2975b6613a894fdd57a24ea65b2684bc12bb9.  Could you send a build log?

**Comment by dsyme** [comment] 2015-01-30 23:41
I see, the problem is that one project was not moved to 2014.1.546. I think merging https://github.com/fsharp/FSharp.Charting/pull/55/ should fix this.

**Comment by dsyme** [comment] 2015-02-05 16:53
I merged #55 and it compiles OK (even after flushing the "packages" directory too).  So I believe this is fixed. 

@mndrake - it would be great if you could check.

**Closed by dsyme** 2015-02-05 16:53 UTC

**Comment by mndrake** [comment] 2015-02-07 03:50
@dsyme Cloning a fresh copy builds correctly now on my machine via ``./build.sh BuildGtk`` using mono. Thanks!
